organized_project_path: /Users/projects_data/project_MLPhenotypesMRIGWAS/organized_data/23_03_30
evaluation_generated_dir: /Users/projects_data/project_MLPhenotypesMRIGWAS/evaluation_generated_data/23_03_30
